var tipuesearch ={"pages":[
	{"title": "Privacy", "text": "A page explaining why privacy matters more than ever today.", "tags": "privacy", "url": "privacy/index.html"},
	{"title": "Tools", "text": "A list of tools you can use to protect your privacy online.", "tags": "tools encryption cryptography", "url": "tools/index.html"},
	{"title": "Signal Private Messenger", "text": "A page about Open Whisper System's app Signal, an easy to use encrypted chat app.", "tags": "encryption textsecure crypto cryptography private chat signal encrypted chat", "url": "tools/signal/index.html"},
	{"title": "Silence", "text": "A page about Silence, a fork of TextSecure (now Signal) that retains SMS encryption.", "tags": "encryption, crypto, cryptography private chat silence encrypted chat sms mms", "url": "tools/silence/index.html"},
	{"title": "Tor", "text": "A page about Tor, an anonymous way to access the internet.", "tags": "tor the onion router anonymous web encryption cryptography", "url": "tools/tor/index.html"},
	{"title": "PGP", "text": "A page about the PGP (Pretty Good Privacy) encryption software.", "tags": "cryptography pgp pretty good privacy email encryption", "url": "tools/pgp/index.html"},
	{"title": "Cryptography", "text": "A page explaining cryptography.", "tags": "encryption cryptography", "url": "crypto/index.html"},
	{"title": "Media for the Layperson", "text": "A list of media to explain related concepts relevent to this issue.", "tags": "media for the layperson videos external encryption cryptography youtube last week tonight", "url": "mediaforthelayperson/index.html"},
	{"title": "Tox", "text": "A page about Tox, a peer-to-peer encrypted text and audio/video calling solution.", "tags": "encryption peer to tox cryptography audio video calling calls encrypted chats private", "url": "tools/tox/index.html"},
	{"title": "The Problem With SMS", "text": "An explanation why SMS is an insecure means of communication.", "tags": "sms insecure problem ss7 flaws", "url": "theproblemwithsms/index.html"},
	{"title": "Secure Passwords", "text": "Create secure, memorable passwords with Diceware.", "tags": "passwords secure diceware memorable easy guide", "url": "securepasswords/index.html"},
	{"title": "Ricochet", "text": "Chat securely and anonymously with Ricochet.", "tags": "tor ricochet cryptography private chat hidden services", "url": "tools/ricochet/index.html"},
        {"title": "Tails", "text": "A secure operating system using Tor", "tags": "tor operating system privacy cryptography anonymity encryption", "url": "tools/tails/index.html"},
]};
